<?php
$cards = [
    [
        'instrument' => 'Piano HEINERSDORFF',
        'model'      => 'Modèle HFF-35-ACAJOU',
        'price'      => '1099,99€',
        'picture'    => 'assets/image-boutique/piano.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Harmonica BLUESY',
        'model'      => 'Modèle One To Ten inox',
        'price'      => '199,99€',
        'picture'    => 'assets/image-boutique/harmonica.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Marimba XYLO',
        'model'      => 'Modèle 42 Golden Medium',
        'price'      => '799,99€',
        'picture'    => 'assets/image-boutique/marimba.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Guitare GIBSON',
        'model'      => 'Modèle SP MIC 2',
        'price'      => '50€',
        'picture'    => 'assets/image-boutique/guitars.jpg',
        'status'     => 'location',
        'available'  => true,
    ],
    [
        'instrument' => 'Violon STRADIVARIUS',
        'model'      => 'Modèle L-STERLING-400',
        'price'      => '80€',
        'picture'    => 'assets/image-boutique/strings.jpg',
        'status'     => 'location',
        'available'  => false,
    ],
    [
        'instrument' => 'Batterie PEARL',
        'model'      => 'Modèle PIM PAM POUM Charlestone',
        'price'      => '75€',
        'picture'    => 'assets/image-boutique/drum.jpg',
        'status'     => 'location',
        'available'  => true,
    ],
    [
        'instrument' => 'Orgue BIG ONE',
        'model'      => 'Inox Pipe 8080',
        'price'      => '500€',
        'picture'    => 'assets/image-boutique/orgue.jpg',
        'status'     => 'location',
        'available'  => true,
    ],
    [
        'instrument' => 'Triangle SQUARE EDGE',
        'model'      => 'Tint 3333 ALU',
        'price'      => '0.99€',
        'picture'    => 'assets/image-boutique/triangle.jpg',
        'status'     => 'location',
        'available'  => false,
    ],
    [
        'instrument' => 'Set de Percussions',
        'model'      => 'Wood first',
        'price'      => '35€',
        'picture'    => 'assets/image-boutique/percu.jpg',
        'status'     => 'location',
        'available'  => false,
    ],
    [
        'instrument' => 'Contrebasse STRADIVARIUS',
        'model'      => 'JAZZ 1955 ACAJOU',
        'price'      => '88€',
        'picture'    => 'assets/image-boutique/contrebasse.jpg',
        'status'     => 'location',
        'available'  => false,
    ],
    [
        'instrument' => 'Table de mixage GUETTA',
        'model'      => 'DJ 2000 8E-50S',
        'price'      => '100€',
        'picture'    => 'assets/image-boutique/mixtable.jpg',
        'status'     => 'location',
        'available'  => true,
    ],
    [
        'instrument' => 'Set de cymbales ZILDJIAN',
        'model'      => 'A0447 GOLD D5-800',
        'price'      => '180€',
        'picture'    => 'assets/image-boutique/cymbal-set.jpg',
        'status'     => 'location',
        'available'  => true,
    ],
    [
        'instrument' => 'Vielle à roue MEDIEV',
        'model'      => '8000 touches 3 cordes 1 roue',
        'price'      => '10000€',
        'picture'    => 'assets/image-boutique/vielle-roue.jpg',
        'status'     => 'location',
        'available'  => false,
    ],
    [
        'instrument' => 'Accordéon ROLAND',
        'model'      => 'PARIS 75 FR-8XB',
        'price'      => '275€',
        'picture'    => 'assets/image-boutique/accordion.jpg',
        'status'     => 'location',
        'available'  => true,
    ],
    [
        'instrument' => 'Banjo TENNESSEE',
        'model'      => 'Western Eastwood Spaghetti',
        'price'      => '320€',
        'picture'    => 'assets/image-boutique/banjo.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Cornemuse KILT',
        'model'      => 'Scotland Green 7 pipes',
        'price'      => '420€',
        'picture'    => 'assets/image-boutique/bagpipes.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Trompette ARMSTRONG',
        'model'      => 'JAZZY MBX3',
        'price'      => '499€',
        'picture'    => 'assets/image-boutique/trompette.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Tuba MELTON',
        'model'      => '2011RA-L Bb',
        'price'      => '799€',
        'picture'    => 'assets/image-boutique/tuba.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Guitare folk GODIN',
        'model'      => 'OMT-28 Naturel',
        'price'      => '120€',
        'picture'    => 'assets/image-boutique/guitar-folk.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Basse RICKENBACKER',
        'model'      => 'Scott Pilgrim POWA <3',
        'price'      => '2000€',
        'picture'    => 'assets/image-boutique/rickenbacker.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Dobro HALLIDAY',
        'model'      => 'Iron Blues Boy JH8',
        'price'      => '240€',
        'picture'    => 'assets/image-boutique/dobro.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
    [
        'instrument' => 'Ukulélé ALOHA',
        'model'      => 'Elypse 4STR-SIb',
        'price'      => '88€',
        'picture'    => 'assets/image-boutique/ukulele.jpg',
        'status'     => 'achat',
        'available'  => true,
    ],
];